name: Perform Manual Backport Audit

on:
  schedule:
  - cron: '10 16 * * 3'

jobs:
  performUnreleasedAudit:
    name: Perform  Manual Backport Audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check unreleased commits
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        ACTION_TYPE: 'needs-manual'